import turtle                   #basic setting

def drawCity(): 
  t = turtle.Turtle()
  window = turtle.Screen()
  window.bgcolor("#e3f5fa")       #background color setting
  t.speed(0)                      #speed of executing codes
  
  t.hideturtle()
  t.penup()
  t.goto(-90,90)
  t.pendown()
  
  def decoration():
    t.forward(7)
    t.right(30)
    t.circle(-7,180)
    t.left(30)
    t.forward(10)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(10)
    t.circle(6,180)
    t.circle(-2,240)
    t.left(50)
    t.circle(-10,180)
    t.left(8)
    t.forward(13)
    t.right(88)
    t.forward(30)
    t.right(90)
    t.forward(29)
    t.right(90)
    t.forward(15)
    t.circle(3,100)
    t.left(80)
    t.forward(10)
    t.circle(-2.25,180)
    t.forward(7)
    
  t.fillcolor("#fae2a2")
  t.begin_fill()
  decoration()
  t.end_fill()
  t.penup()
  
  t.goto(-75,55)
  t.pendown()
  t.forward(150)
  t.penup()
  t.goto(90,90)
  t.pendown()
  t.fillcolor("#fae2a2")
  t.begin_fill()
  decoration()
  t.end_fill()
  t.penup()
  t.goto(-75,53)
  t.pendown()
  t.forward(150)
  t.penup()
  t.goto(-107,53)
  t.pendown()
  t.right(90)
  t.forward(5)
  t.left(90)
  t.forward(213)
  t.left(90)
  t.forward(5)
  t.penup()
  
  t.goto(-107,50)                 #roof
  t.pendown()
  t.fillcolor("#c96d65")
  t.begin_fill()
  t.left(150)
  t.circle(-90,60)
  t.left(150)
  t.forward(30)
  t.left(30)
  t.forward(315)
  t.left(30)
  t.forward(30)
  t.left(150)
  t.circle(-90,60)
  t.end_fill()
  t.penup()
  
  t.goto(-158,-8)
  t.pendown()
  t.fillcolor("#b52418")
  t.begin_fill()
  t.left(150)
  t.forward(30)
  t.left(90)
  t.forward(315)
  t.left(90)
  t.forward(30)
  t.end_fill()
  t.penup()
  
  def yellow_window():
    t.pendown()
    for repetition in range (2):
      t.right(90)
      t.forward(130)
      t.right(90)
      t.forward(13)
      
  t.goto(-158,-15)
  t.pendown()
  t.fillcolor("#ffe347")
  t.begin_fill()
  yellow_window()
  t.end_fill()
  t.penup()
  
  t.goto(27,-15)
  t.pendown()
  t.fillcolor("#ffe347")
  t.begin_fill()
  yellow_window()
  t.end_fill()
  t.penup()
  
  t.goto(-158,-39)
  t.pendown()
  t.fillcolor("#c96d65")
  t.begin_fill()
  t.left(120)
  t.circle(-75,40)
  t.left(150)
  t.forward(30)
  t.left(40)
  t.forward(370)
  t.left(40)
  t.forward(30)
  t.left(150)
  t.circle(-75,40)
  t.end_fill()
  t.penup()
  
  t.goto(-175,-68)
  t.pendown()
  t.left(120)
  t.fillcolor("#ffbc47")
  t.begin_fill()
  for repetition in range(2):
    t.forward(40)
    t.left(90)
    t.forward(355)
    t.left(90)
  t.end_fill()
  t.penup()
  
  def yellow_pillars():
    t.fillcolor("#ffe347")
    t.begin_fill()
    t.right(90)
    for repetition in range(2):
      t.forward(10)
      t.left(90)
      t.forward(40)
      t.left(90)
    t.end_fill()
    
  def yellow_pillars_column(x=0,y=0):
    t.goto(x,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+30,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+60,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+90,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+120,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+150,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+180,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+210,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+240,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+270,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+300,y)
    yellow_pillars()
    t.left(90)
    t.goto(x+330,y)
    yellow_pillars()
    t.left(90)
  
  yellow_pillars_column(-158,-68)
  t.penup()
  
  
  t.goto(-23,-120)
  t.fillcolor("#f2e8d5")
  t.begin_fill()
  t.pendown()
  t.right(6)
  t.forward(60)
  t.left(97)
  t.forward(60)
  t.left(98)
  t.forward(60)
  t.left(82)
  t.forward(43)
  t.end_fill()
  t.penup()
  
  t.goto(-35,-123)
  t.pendown()
  t.fillcolor("#ccc8c0")
  t.begin_fill()
  t.left(75)
  t.forward(57)
  t.right(74)
  t.forward(40)
  t.right(120)
  t.forward(66)
  t.right(63)
  t.forward(25)
  t.end_fill()
  t.penup()
  
  def left_stairs(x=0,y=0,length=27):
    t.goto(x,y)
    t.left(3)
    t.pendown()
    t.forward(length)
    t.penup()
    t.goto(x-7,y-10)
    t.pendown()
    t.forward(length+4)
    t.penup()
    t.goto(x-14,y-20)
    t.pendown()
    t.forward(length+6)
    t.penup()
    t.goto(x-19,y-30)
    t.right(1)
    t.pendown()
    t.forward(length+9)
    t.penup()
    t.goto(x-25,y-40)
    t.pendown()
    t.forward(length+12)
    t.penup()
  
  left_stairs(-63,-133)
  
  t.penup()
  t.goto(37,-123)
  t.pendown()
  t.fillcolor("#ccc8c0")
  t.begin_fill()
  t.right(75)
  t.forward(60)
  t.left(74)
  t.forward(40)
  t.left(120)
  t.forward(68)
  t.left(63)
  t.forward(25)
  t.end_fill()
  t.penup()
  
  def right_stairs(x=0,y=0,length=27):
    t.goto(x,y)
    t.pendown()
    t.right(1)
    t.forward(-length)
    t.penup()
    t.goto(x+4,y-10)
    t.pendown()
    t.right(1)
    t.forward(-length-4)
    t.penup()
    t.goto(x+8,y-20)
    t.pendown()
    t.right(1)
    t.forward(-length-6)
    t.penup()
    t.goto(x+12,y-30)
    t.pendown()
    t.right(1)
    t.forward(-length-9)
    t.penup()
    t.goto(x+16,y-40)
    t.pendown()
    t.forward(-length-12)
    t.penup()
  
  right_stairs(39,-133)
  t.penup()
  
  t.goto(-176,-107)
  t.pendown()
  t.fillcolor("#a3a099")
  t.begin_fill()
  t.forward(15)
  t.left(90)
  t.forward(15)
  t.left(91.25)
  t.forward(385)
  t.left(90)
  t.forward(15)
  t.left(90)
  t.forward(15)
  t.end_fill()
  t.penup()
  
  def left_later_stairs(x=0,y=0,length=0):
    t.goto(x,y)
    t.pendown()
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(length)
    t.penup()
    
    t.goto(x-30,y-30)
    t.pendown()
    t.forward(length-10)
    t.penup()
   
    t.goto(x-30,y-45)
    t.pendown()
    t.forward(length-15)
    t.penup()
    
    t.goto(x-30,y-57)
    t.pendown()
    t.forward(length+70)
    
  def right_later_stairs():
    t.goto(177,-123)
    t.pendown()
    t.forward(50)
    t.penup()
    
    t.goto(70,-137)
    t.pendown()
    t.forward(140)
    t.penup()
    
    t.goto(77,-152)
    t.pendown()
    t.forward(140)
    t.penup()
    
    t.goto(85,-167)
    t.pendown()
    t.forward(140)
    t.penup()
   
    t.goto(90,-181)
    t.pendown()
    t.forward(300)
    t.penup()
  
  left_later_stairs(-176,-122,140)
  t.penup()
  right_later_stairs()
  t.penup()
  
  t.goto(0,0)
  
  t.hideturtle()                  #hideturtle
  t.penup()
  t.goto(50,-70)
  
  def talloval(r):                # Verticle Oval
      t.left(45)
      for loop in range(2):       # Draws 2 halves of ellipse
          t.circle(r,90)          # Long curved part
          t.circle(r/2,90)
  t.color("#695e4c")              # Face (line) color
  t.fillcolor("#fcecc7")          # Face color (inside)
  t.begin_fill()    
  t.pendown()
  talloval(120)                   
  t.end_fill()
  t.penup()
  t.goto(6,80)                    # Start Hair
  t.left(90)
  
  import avatar
  import eclothes